'use client';
import {useEffect,useMemo,useState} from 'react';
import AppShell from './AppShell';
import {api} from '../lib';
import {Modal,SearchBox,StatusBadge} from './AdminUI';

type Field={key:string;label:string;type?:'text'|'textarea'|'number'|'select'|'checkbox'|'date'|'email'|'url'|'password';required?:boolean;options?:string[];full?:boolean;placeholder?:string};
type CrudProps={title:string;subtitle?:string;path:string;createPath?:string;fields:Field[];columns:{key:string;label:string}[];canDelete?:boolean;deletePath?:(id:string)=>string;createLabel?:string;normalizeCreate?:(v:any)=>any;normalizeUpdate?:(v:any)=>any;getId?:(x:any)=>string;transformRows?:(x:any)=>any[];protectedKey?:(x:any)=>boolean};
const get=(o:any,k:string)=>k.split('.').reduce((a,p)=>a?.[p],o);
export default function CrudPage({title,subtitle,path,createPath,fields,columns,canDelete=true,deletePath,createLabel='إضافة جديد',normalizeCreate,normalizeUpdate,getId,transformRows,protectedKey}:CrudProps){
 const [rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[err,setErr]=useState(''),[q,setQ]=useState(''),[editing,setEditing]=useState<any|null>(null),[fresh,setFresh]=useState(false),[busy,setBusy]=useState(false);
 const idOf=getId||((x:any)=>String(x.id));
 const load=()=>{setLoading(true);setErr('');api(path).then(x=>setRows(transformRows?transformRows(x):Array.isArray(x)?x:[])).catch(e=>setErr(e.message)).finally(()=>setLoading(false))};
 useEffect(load,[]);
 const filtered=useMemo(()=>rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q.toLowerCase())),[rows,q]);
 const save=async(v:any)=>{setBusy(true);try{const normalized=(editing?(normalizeUpdate?normalizeUpdate(v):v):(normalizeCreate?normalizeCreate(v):v))||{};const payload=Object.fromEntries(Object.entries(normalized).filter(([_,x])=>x!==undefined&&x!==''));const saved=await api(editing?`${path}/${idOf(editing)}`:(createPath||path),{method:editing?'PUT':'POST',body:JSON.stringify(payload)});setRows(old=>editing?old.map(x=>idOf(x)===idOf(editing)?saved:x):[saved,...old]);setEditing(null);setFresh(false);await load()}catch(e:any){alert(e.message)}finally{setBusy(false)}};
 const remove=async(r:any)=>{if(!canDelete||protectedKey?.(r))return;if(!confirm('تأكيد الحذف؟'))return;try{await api(deletePath?deletePath(idOf(r)):`${path}/${idOf(r)}`,{method:'DELETE'});setRows(old=>old.filter(x=>idOf(x)!==idOf(r)))}catch(e:any){alert(e.message)}};
 return <AppShell title={title} subtitle={subtitle}><div className="toolbar"><SearchBox value={q} onChange={setQ}/><button className="btn" onClick={()=>{setEditing(null);setFresh(true)}}>+ {createLabel}</button><button className="btn secondary" onClick={load}>تحديث</button></div>{err&&<div className="error">{err}</div>}<div className="card table-wrap"><table className="table"><thead><tr>{columns.map(c=><th key={c.key}>{c.label}</th>)}<th>الإجراءات</th></tr></thead><tbody>{loading?<tr><td colSpan={columns.length+1} className="empty">جارٍ التحميل...</td></tr>:filtered.length===0?<tr><td colSpan={columns.length+1} className="empty">لا توجد بيانات</td></tr>:filtered.map(r=><tr key={idOf(r)}>{columns.map(c=>{const value=get(r,c.key);if(c.key==='status'||c.key==='role')return <td key={c.key}><StatusBadge tone={String(value).includes('SUSP')||String(value).includes('CANCEL')||String(value).includes('LOST')?'red':String(value).includes('ACTIVE')||String(value).includes('DONE')||String(value).includes('PAID')?'green':'blue'}>{value||'—'}</StatusBadge></td>;if(c.key==='active'||c.key==='published'||c.key==='isMasterSuperAdmin')return <td key={c.key}><StatusBadge tone={value?'green':'red'}>{value?'نعم':'لا'}</StatusBadge></td>;return <td key={c.key}>{value instanceof Date?value.toLocaleDateString('ar'):String(value??'—')}</td>})}<td><div className="actions"><button className="btn secondary" onClick={()=>setEditing(r)}>تعديل</button>{canDelete&&!protectedKey?.(r)&&<button className="btn danger" onClick={()=>remove(r)}>حذف</button>}</div></td></tr>)}</tbody></table></div>{(editing||fresh)&&<Modal title={editing?'تعديل':'إضافة'} onClose={()=>{setEditing(null);setFresh(false)}} wide><EntityForm key={editing?.id||'new'} fields={fields} initial={editing||{}} busy={busy} editing={!!editing} onSave={save}/></Modal>}</AppShell>
}
function EntityForm({fields,initial,busy,onSave,editing}:{fields:Field[];initial:any;busy:boolean;editing:boolean;onSave:(v:any)=>void}){const[v,setV]=useState<any>({...initial});const set=(k:string,x:any)=>setV((o:any)=>({...o,[k]:x}));return <div className="form-grid">{fields.map(f=><label key={f.key} className={f.full?'full':''}>{f.label}{f.type==='textarea'?<textarea className="textarea" value={typeof v[f.key]==='object'&&v[f.key]!==null?JSON.stringify(v[f.key],null,2):(v[f.key]??'')} onChange={e=>set(f.key,e.target.value)} placeholder={f.placeholder}/>:f.type==='select'?<select className="select" value={v[f.key]??''} onChange={e=>set(f.key,e.target.value)}><option value="">— اختر —</option>{(f.options||[]).map(o=><option key={o} value={o}>{o}</option>)}</select>:f.type==='checkbox'?<span className="check"><input type="checkbox" checked={!!v[f.key]} onChange={e=>set(f.key,e.target.checked)}/> مفعّل</span>:<input className="input" type={f.type==='number'?'number':f.type==='date'?'date':f.type==='email'?'email':f.type==='url'?'url':f.type==='password'?'password':'text'} value={f.type==='date'&&v[f.key]?String(v[f.key]).slice(0,10):(v[f.key]??'')} onChange={e=>set(f.key,f.type==='number'?Number(e.target.value):e.target.value)} required={f.required} placeholder={f.placeholder}/>}</label>)}<div className="actions full"><button className="btn" disabled={busy} onClick={()=>onSave(v)}>{busy?'جارٍ الحفظ...':editing?'حفظ التعديل':'حفظ'}</button></div></div>}
